{% set name = "gstlal-inspiral" %}
{% set version = "1.9.2" %}

# dependencies
{% set lscsoft_glue_version = "2.0.0" %}
{% set gobject_introspection_version = "1.30.0" %}
{% set gstlal_version = "1.9.0" %}
{% set gstlal_ugly_version = "1.9.1" %}
{% set lal_version = "7.1.0" %}
{% set lalinspiral_version = "2.0.0" %}
{% set lalmetaio_version = "2.0.0" %}
{% set ligo_gracedb_version = "2.7.5" %}
{% set ligo_scald_version = "0.7.2" %}
{% set ligo_segments_version = "1.2.0" %}
{% set python_ligo_lw_version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: a0fe036111d012ccf77454d618c686c8444cc4bc29c92337a4c345649a2b09a1
  patches:
    - link-gsl.patch
    - no-link-libpython.patch  # [osx]

build:
  error_overdepending: true
  error_overlinking: true
  ignore_run_exports:
    # needed by configure, but not used
    - liblalmetaio
    - liblalinspiral
    # not linked, but needed at runtime
    - gst-plugins-base
    - gobject-introspection
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [unix]
    - pkg-config >=0.18.0  # [unix]
  host:
    - glib
    - gobject-introspection >={{ gobject_introspection_version }}
    - gsl
    - gstreamer
    - gstlal >={{ gstlal_version }}
    - liblal >={{ lal_version }}
    - liblalinspiral >={{ lalinspiral_version }}
    - liblalmetaio >={{ lalmetaio_version }}
    - numpy
    - python
  run:
    - gobject-introspection >={{ gobject_introspection_version }}
    - gsl
    - gstreamer
    - gst-plugins-base
    - gstlal >={{ gstlal_version }}
    - gstlal-ugly >={{ gstlal_ugly_version }}
    - h5py
    - lalapps
    - liblal >={{ lal_version }}
    - liblalinspiral >={{ lalinspiral_version }}
    - liblalmetaio >={{ lalmetaio_version }}
    - ligo-gracedb >={{ ligo_gracedb_version }}
    - ligo-segments >={{ ligo_segments_version }}
    - ligo-scald >={{ ligo_scald_version }}
    - lscsoft-glue >={{ lscsoft_glue_version }}
    - {{ pin_compatible('numpy') }}
    - pandas >=0.17.1
    - python
    - python-lal >={{ lal_version }}
    - python-lalinspiral >={{ lalinspiral_version }}
    - python-ligo-lw >={{ python_ligo_lw_version }}
    - scipy

test:
  imports:
    - gstlal.chirptime
    - gstlal.far
    - gstlal.snglinspiraltable
  commands:
    - export GSTLAL_FIR_WHITEN=0
    - export TMPDIR=$(python -c "import tempfile; print(tempfile.gettempdir())")
    # these imports need the GSTLAL_FIR_WHITEN variable
    - python -c "import gstlal.inspiral"
    - python -c "import gstlal.inspiral_pipe"
    # check executables
    - gstlal_inspiral --help
    - gstlal_inspiral_pipe --help
    - gstlal_ll_inspiral_pipe --help
    - gstlal_svd_bank --help

about:
  home: https://lscsoft.docs.ligo.org/gstlal/
  dev_url: https://git.ligo.org/lscsoft/gstlal/
  doc_url: https://lscsoft.docs.ligo.org/gstlal/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: GStreamer for GW data analysis (inspiral parts)
  description: |
    This package provides a variety of gstreamer elements for
    gravitational-wave data analysis and some libraries to help write such
    elements.  The code here sits on top of several other libraries, notably
    the LIGO Algorithm Library (LAL), FFTW, the GNU Scientific Library (GSL),
    and, of course, GStreamer.
    This package contains plugins, libraries, and programs for inspiral data
    analysis.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - myNameIsPatrick
