{% set name = "gstlal-inspiral" %}
{% set version = "1.11.0" %}

# dependencies
{% set gobject_introspection_version = "1.30.0" %}
{% set gstlal_version = "1.10.0" %}
{% set gstlal_ugly_version = "1.10.0" %}
{% set lal_version = "7.2.4" %}
{% set lalinspiral_version = "3.0.2" %}
{% set lalmetaio_version = "3.0.2" %}
{% set ligo_gracedb_version = "2.7.5" %}
{% set ligo_scald_version = "0.8.1" %}
{% set ligo_segments_version = "1.2.0" %}
{% set python_ligo_lw_version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/{{ name }}-{{ version }}.tar.gz
  sha256: c5e1b167bfb118ae2fcc0355108997ad4425774292a7d33a727a1b8ebe55d338
  patches:
    - py-compile-imp.patch
    - pyobject_head_init.patch
    - link-gsl.patch
    - no-link-libpython.patch  # [osx]

build:
  error_overlinking: true
  ignore_run_exports:
    # needed by configure, but not used
    - liblalmetaio
    - liblalinspiral
    # not linked, but needed at runtime
    - gst-plugins-base
    - gobject-introspection
  ignore_run_exports_from:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
  number: 3
  # lalinspiral is not available for Python 3.9
  skip: true  # [win or py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make  # [unix]
    - pkg-config >=0.18.0  # [unix]
  host:
    - glib
    - gobject-introspection >={{ gobject_introspection_version }}
    - gsl
    - gstreamer
    - gstlal >={{ gstlal_version }}
    - liblal >={{ lal_version }}
    - liblalinspiral >={{ lalinspiral_version }}
    - liblalmetaio >={{ lalmetaio_version }}
    - numpy
    - python
  run:
    - gobject-introspection >={{ gobject_introspection_version }}
    - gsl
    - gstreamer
    - gst-plugins-base
    - gstlal >={{ gstlal_version }}
    - gstlal-ugly >={{ gstlal_ugly_version }}
    - h5py
    - liblal >={{ lal_version }}
    - liblalinspiral >={{ lalinspiral_version }}
    - liblalmetaio >={{ lalmetaio_version }}
    - ligo-gracedb >={{ ligo_gracedb_version }}
    - ligo-segments >={{ ligo_segments_version }}
    - ligo-scald >={{ ligo_scald_version }}
    - {{ pin_compatible('numpy') }}
    - pandas >=0.17.1
    - python
    - python-lal >={{ lal_version }}
    - python-lalinspiral >={{ lalinspiral_version }}
    - python-ligo-lw >={{ python_ligo_lw_version }}
    - scipy

test:
  imports:
    - gstlal.chirptime
    - gstlal.far
    - gstlal.snglinspiraltable
  commands:
    - export GSTLAL_FIR_WHITEN=0
    - export TMPDIR=$(python -c "import tempfile; print(tempfile.gettempdir())")
    # these imports need the GSTLAL_FIR_WHITEN variable
    - python -c "import gstlal.inspiral"
    # check executables
    - gstlal_inspiral --help
    - gstlal_inspiral_workflow --help
    - gstlal_inspiral_svd_bank --help
    - gstlal_ll_inspiral_workflow --help

about:
  home: https://lscsoft.docs.ligo.org/gstlal/
  dev_url: https://git.ligo.org/lscsoft/gstlal/
  doc_url: https://lscsoft.docs.ligo.org/gstlal/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: GStreamer for GW data analysis (inspiral parts)
  description: |
    This package provides a variety of gstreamer elements for
    gravitational-wave data analysis and some libraries to help write such
    elements.  The code here sits on top of several other libraries, notably
    the LIGO Algorithm Library (LAL), FFTW, the GNU Scientific Library (GSL),
    and, of course, GStreamer.
    This package contains plugins, libraries, and programs for inspiral data
    analysis.

extra:
  recipe-maintainers:
    - aepace
    - duncanmmacleod
    - myNameIsPatrick
